ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS cancellation_policy_snapshot TEXT,
  ADD COLUMN IF NOT EXISTS refund_npr INTEGER DEFAULT 0;
